# require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '11.0'
# install! 'cocoapods', :deterministic_uuids => false

# target 'ivacy' do
#   config = use_native_modules!

#   # Flags change depending on the env values.
#   flags = get_default_flags()

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # to enable hermes on iOS, change `false` to `true` and then install pods
#     :hermes_enabled => flags[:hermes_enabled],
#     :fabric_enabled => flags[:fabric_enabled],
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )
#   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
#   target 'ivacyTests' do
#     inherit! :complete
#     # Pods for testing
#   end

#   # Enables Flipper.
#   #
#   # Note that if you have use_frameworks! enabled, Flipper will not work and
#   # you should disable the next line.
#   use_flipper!()

#   post_install do |installer|
#     react_native_post_install(installer)
#     __apply_Xcode_12_5_M1_post_install_workaround(installer)
#   end
# end
$FirebaseSDKVersion = '9.3.0'
$RNFirebaseAsStaticFramework = true
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
rn_maps_path = '../node_modules/react-native-maps'
permissions_path = '../node_modules/react-native-permissions/ios'
platform :ios, '15.2'
# platform :ios, '14.4.2'

target 'ivacy' do
  config = use_native_modules!
  pod 'GoogleMaps'
  pod 'Stripe'
  pod 'GooglePlaces'
    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'react-native-restart', :path => '../node_modules/react-native-restart'
  # pod 'moralis'
  # pod 'react-moralis'
  # pod 'Firebase/Messaging'
  # pod 'FirebaseCore', '9.2.0', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master' # eg 6.31.0
  pod 'react-native-maps' ,:path => '../node_modules/react-native-maps' # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
#   pod 'Firebase', :modular_headers => true
# pod 'FirebaseCoreInternal', :modular_headers => true
# pod 'GoogleUtilities', :modular_headers => true
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  target 'ivacyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end